Rename RISCV environment variable to RISCV_XHEEP (#765)
* Rename RISCV environment variable to RISCV_XHEEP

* fix RISCV_XHEEP variable in github actions

* re-vendor

* re-vendor after merge

* undo unwanted changes

* Revert wrong RISCV change

* Fix formatting of RISCV variables in Makefile

* also update riscv.cmake

* add docs warning

---------

Co-authored-by: David Mallasén Quintana <david.mallasen@epfl.ch>

diff --git a/.github/workflows/building.yml b/.github/workflows/building.yml
--- a/.github/workflows/building.yml
+++ b/.github/workflows/building.yml
@@ -10,6 +10,15 @@ jobs:
     steps:
       - name: Checkout the pushed code. 
         uses: actions/checkout@v3        
+
+      - name: Detect RISCV toolchain and export
+        run: |
+          tool=$(command -v riscv32-unknown-elf-gcc || true)
+          if [ -z "$tool" ]; then echo "RISC-V toolchain not found"; exit 1; fi
+          root=$(dirname "$(dirname "$tool")")
+          echo "RISCV_XHEEP=$root" >> $GITHUB_ENV
+          echo "PATH=$root/bin:$PATH" >> $GITHUB_ENV
+
       - name: Configure the job container and compile all apps.
         run: |
           # Create the virtual environment and install the requirements. 
@@ -20,5 +29,4 @@ jobs:
 
           # The MCU is generated with various memory banks to avoid example code not fitting.
           make mcu-gen X_HEEP_CFG=configs/ci.hjson
-
           python3 test/test_apps/test_apps.py --compile-only
diff --git a/.github/workflows/simulate.yml b/.github/workflows/simulate.yml
--- a/.github/workflows/simulate.yml
+++ b/.github/workflows/simulate.yml
@@ -10,6 +10,14 @@ jobs:
     steps:
       - name: Checkout the pushed code. 
         uses: actions/checkout@v3
+      - name: Detect RISCV toolchain and export
+        shell: bash
+        run: |
+          tool=$(command -v riscv32-unknown-elf-gcc || true)
+          if [ -z "$tool" ]; then echo "RISC-V toolchain not found"; exit 1; fi
+          root=$(dirname "$(dirname "$tool")")
+          echo "RISCV_XHEEP=$root" >> $GITHUB_ENV
+          echo "PATH=$root/bin:$PATH" >> $GITHUB_ENV
       - name: Configure the job container and simulate all apps
         run: |
           # Create the virtual environment and install the requirements. 
